// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75NsG4KNthgYxvuAPNWnmMDV-i4I9HCY',
    appId: '1:636975149329:web:8a8a903a69f7f10e4c5cb0',
    messagingSenderId: '636975149329',
    projectId: 'megamall-e3cd1',
    authDomain: 'megamall-e3cd1.firebaseapp.com',
    storageBucket: 'megamall-e3cd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_BW8df_cTMr5tngALj6X3LK1S4WQz-U',
    appId: '1:636975149329:android:83fe9784966fceaf4c5cb0',
    messagingSenderId: '636975149329',
    projectId: 'megamall-e3cd1',
    storageBucket: 'megamall-e3cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9J4d68j8Jcs6O3MKWJyAy4I14PstNx8Y',
    appId: '1:636975149329:ios:b3fe1ad9e7cd7a914c5cb0',
    messagingSenderId: '636975149329',
    projectId: 'megamall-e3cd1',
    storageBucket: 'megamall-e3cd1.appspot.com',
    iosClientId: '636975149329-7q90h144o3ueem54c8l3mbf4h1enuoo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.megamall',
  );
}
